# Generated by Django 3.0.1 on 2023-01-15 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
